Added experimental recipe support

diff --git a/data/AppRun b/data/AppRun
--- a/data/AppRun
+++ b/data/AppRun
@@ -17,17 +17,29 @@ APPIMAGE_DIR=$(dirname "${APPIMAGE}")
 
 #---------------------------------------------------------------------------
 
-[ -z "${BOTTLE_NAME}" ] && {
-  export BOTTLE_NAME="$(echo ${1} | sed 's/[[:space:]]//g')"
-  shift
-}
-
-#---------------------------------------------------------------------------
-
 . ${HERE}/BottleTool.sh
 . ${HERE}/AppDirTool.sh
 . ${HERE}/FlagsTool.sh
 . ${HERE}/Help.sh
+. ${HERE}/Recipe.sh
+
+#---------------------------------------------------------------------------
+
+[ "${OPTION}" = "--recipe" ] && {
+  [ ! -f "${1}" ] && {
+    echo "Error: Recipe file '${1}' not found"
+    exit 1
+  }
+  recipe.run "${1}"
+  exit ${?}
+}
+
+#---------------------------------------------------------------------------
+
+[ -z "${BOTTLE_NAME}" ] && {
+  export BOTTLE_NAME="$(echo ${1} | sed 's/[[:space:]]//g')"
+  shift
+}
 
 #---------------------------------------------------------------------------
 
